DigitalAppraiser/Models/DBModels/LoanDetails.cs
namespace DigitalAppraiser.Models.DBModels
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("LoanDetails")]
    public class LoanDetails
    {
        public int ID { get; set; }
        public string LoanId { get; set; }
        public int CustomerId { get; set; }
        public int LoanType { get; set; }
        public decimal LoanAmount { get; set; }
        public decimal Interest { get; set; }
        public decimal EMI { get; set; }
        public decimal? CollectedAmount { get; set; }
        public decimal? CollectedInterest { get; set; }
        public int? NoOfDays { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTimeOffset CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTimeOffset ModifiedOn { get; set; }
    }
}

DigitalAppraiser/Models/DBModels/OrnamentDetails.cs
namespace DigitalAppraiser.Models.DBModels
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("OrnamentDetails")]
    public class OrnamentDetails
    {
        [Key]
        public int OrnamentId { get; set; }
        [Required]
        public string Ornament { get; set; }
        [Required]
        public int Quantity { get; set; }
        [Required]
        public decimal GrossWeight { get; set; }
        public decimal StoneWeight { get; set; }
        public int Quality { get; set; }
        [Required]
        public decimal NetWeight { get; set; }
        [Required]
        public decimal MarketPrice { get; set; }
        public int CustomerId { get; set; }
        public int LoanType { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTimeOffset CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTimeOffset ModifiedOn { get; set; }
    }
}

DigitalAppraiser/Models/DBModels/PaytmResponse.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DigitalAppraiser.Models.DBModels
{
    [Table("LnSmithPaymentDetails")]
    public class PaytmResponse
    {
        [Key]
        public int Id { get; set; }
        public int AppraiserId { get; set; }
        public string MID { get; set; }
        public string ORDERID { get; set; }
        public string TXNAMOUNT { get; set; }
        public string CURRENCY { get; set; }
        public string TXNID { get; set; }
        public string BANKTXNID { get; set; }
        public string STATUS { get; set; }
        public string RESPCODE { get; set; }
        public string RESPMSG { get; set; }
        public string TXNDATE { get; set; }
        public string GATEWAYNAME { get; set; }
        public string BANKNAME { get; set; }
        public string PAYMENTMODE { get; set; }
        public string CHECKSUMHASH { get; set; }
    }
}

DigitalAppraiser/Models/DBModels/TodayRate.cs
namespace DigitalAppraiser.Models.DBModels
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TodayRate")]
    public partial class TodayRate
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public decimal Rate { get; set; }
        public int? BankId { get; set; }
        public int? AppraiserId { get; set; }
        public string CreatedBy { get; set; }
        public DateTimeOffset CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTimeOffset ModifiedOn { get; set; }
        public bool IsActive { get; set; }
        public virtual AppraiserDetail AppraiserDetail { get; set; }
    }
}

DigitalAppraiser/Controllers/ApraiserController.cs
using DigitalAppraiser.Models.DBModels;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using OfficeOpenXml;
using OfficeOpenXml.FormulaParsing.Excel.Functions.DateTime;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using BL = DigitalAppraiser.BuinessLogic;
using Models = DigitalAppraiser.Models;

namespace DigitalAppraiser.Controllers
{
    [Authorize]
    [SessionTimeoutAttribute]
    public class ApraiserController : Controller
    {
        // GET: Apraiser
        public ActionResult DashBoard()
        {
            BL.Interfaces.AppriserInterface bl = new BL.Implementation.AppraiserClass();
            //int AppraiserId = LogedUser.AppraiserId.Value;
            //var model = bl.GetUserDateRates(AppraiserId);
            return View();
        }
        public ActionResult TodayRate()
        {
            BL.Interfaces.AppriserInterface bl = new BL.Implementation.AppraiserClass();
            int AppraiserId = LogedUser.AppraiserId.Value;
            var model = bl.GetUserDateRates(AppraiserId);
            return View(model);
        }
        [HttpPost]
        public ActionResult TodayRate(Models.ViewModels.TodayRateModel model)
        {
            BL.Interfaces.AppriserInterface bl = new BL.Implementation.AppraiserClass();
            if (ModelState.IsValid == true)
            {
                string userName = LogedUser.UserName;
                var result = bl.SaveTodayRate(model, userName);
                return RedirectToAction("ProcessLoan");
            }
            int AppraiserId = LogedUser.AppraiserId.Value;
            model = bl.GetUserDateRates(AppraiserId);
            return View(model);
        }
        [HttpGet]
        public ActionResult ProcessLoan()
        {
            BL.Interfaces.AppriserInterface bl = new BL.Implementation.AppraiserClass();
            int AppraiserId = LogedUser.AppraiserId.Value;
            Models.ViewModels.ProcessLoanModel model = new Models.ViewModels.ProcessLoanModel();
            model.isSelfEnable = bl.IsSelfEnabled(AppraiserId);
            model.bankCustomer = new Models.ViewModels.BankCustomerModel();
            model.bankCustomer.Banks = bl.GetAppraiserBanks(AppraiserId);
            model.selfCustomer = new Models.ViewModels.SelfCustomerModel();
            int[] list = Enumerable.Range(1, 50).ToArray();
            model.selfCustomer.Quantity = list.Select(x => new SelectListItem
            {
                Value = x.ToString(),
                Text = x.ToString()
            });
            var relList = new[] { new { Name = "Son of", Value = 1 }, new { Name = "Daughter of", Value = 2 }, new { Name = "Wife of", Value = 3 } };
            //model.BankId = BankId;
            model.bankCustomer.RelationTypes = relList.Select(x => new SelectListItem
            {
                Value = x.Value.ToString(),
                Text = x.Name
            });
            model.bankCustomer.Quantity = list.Select(x => new SelectListItem
            {
                Value = x.ToString(),
                Text = x.ToString()
            });
            ViewBag.TodayRate = bl.GetTodayRate(AppraiserId, 1);
            model.bankCustomer.bankCustomer = new BankCustomerDetails();
            model.bankCustomer.ornamentDetails = new OrnamentDetails();
            model.selfCustomer.selfCustomer = new SelfCustomerDetails();
            model.selfCustomer.ornamentDetails = new OrnamentDetails();
            model.isFirstLoad = "True";
            return View(model);
        }
        [HttpGet]
        public ActionResult SelfCustomer()
        {
            var model = new Models.ViewModels.SelfCustomerModel();
            return PartialView("SelfCustomer", model);
        }
        [HttpPost]
        public ActionResult SelfCustomer(Models.ViewModels.SelfCustomerModel model)
        {
            BL.Interfaces.AppriserInterface bl = new BL.Implementation.AppraiserClass();
            int AppraiserId = LogedUser.AppraiserId.Value;
            string userName = LogedUser.UserName;
            ModelState["ornamentDetails.StoneWeight"].Errors.Clear();
            if (ModelState.IsValid == true)
            {
                int customerId = bl.SaveSelfCustomerDetails(model, AppraiserId, userName);
                return RedirectToAction("Estimation", new { customerId = customerId, LoanType = 1 });
            }
            else
            {
                Models.ViewModels.ProcessLoanModel procModel = new Models.ViewModels.ProcessLoanModel();
                procModel.bankCustomer = new Models.ViewModels.BankCustomerModel();
                procModel.bankCustomer.Banks = bl.GetAppraiserBanks(AppraiserId);
                procModel.selfCustomer = model;
                procModel.isSelfEnable = true;
                int[] list = Enumerable.Range(1, 50).ToArray();
                procModel.selfCustomer.Quantity = list.Select(x => new SelectListItem
                {
                    Value = x.ToString(),
                    Text = x.ToString()
                });
                var relList = new[] { new { Name = "Son of", Value = 1 }, new { Name = "Daughter of", Value = 2 }, new { Name = "Wife of", Value = 3 } };
                //model.BankId = BankId;
                procModel.bankCustomer.RelationTypes = relList.Select(x => new SelectListItem
                {
                    Value = x.Value.ToString(),
                    Text = x.Name
                });
                procModel.bankCustomer.Quantity = list.Select(x => new SelectListItem
                {
                    Value = x.ToString(),
                    Text = x.ToString()
                });
                procModel.ActiveTab = "Self";
                procModel.isFirstLoad = "False";
                procModel.bankCustomer.bankCustomer = new BankCustomerDetails();
                procModel.bankCustomer.ornamentDetails = new OrnamentDetails();
                return View("ProcessLoan", procModel);
            }
        }
        [HttpGet]
        public ActionResult GetTodayRate(int bankId)
        {
            BL.Interfaces.AppriserInterface bl = new BL.Implementation.AppraiserClass();
            int AppraiserId = LogedUser.AppraiserId.Value;
            TodayRate todayRate = new TodayRate();
            todayRate = bl.GetTodayRate(AppraiserId, bankId);
            return Json(todayRate, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult Estimation(int customerId, int LoanType)
        {
            BL.Interfaces.AppriserInterface bl = new BL.Implementation.AppraiserClass();
            Models.ViewModels.OrnamentDetailsModel model = new Models.ViewModels.OrnamentDetailsModel();
            model.customerId = customerId;
            string userName = LogedUser.UserName;
            model.ornamentsList = bl.GetOrnamentDetails(customerId, LoanType).ornamentsList;
            model.loanDetails = new Models.DBModels.LoanDetails();
            model.loanDetails.CustomerId = customerId;
            model.loanDetails.CreatedBy = userName;
            model.loanDetails.ModifiedBy = userName;
            model.loanDetails.LoanType = LoanType;
            var customer = bl.customerDetails(model.loanDetails.LoanType, customerId);
            model.CustomerName = customer.selfCustomer.Name;
            model.MobileNumber = customer.selfCustomer.MobileNumber;
            model.Address = customer.selfCustomer.Address;
            model.Aadhar = customer.selfCustomer.UANNumber;
            return View(model);
        }
        [HttpPost]
        public ActionResult GenerateLoan(Models.DBModels.LoanDetails model)
        {
            BL.Interfaces.AppriserInterface bl = new BL.Implementation.AppraiserClass();
            int AppraiserId = LogedUser.AppraiserId.Value;
            var returnModel = bl.GenerateLoan(model, AppraiserId);
            if (returnModel.loanDetails.LoanType == 1)
            {
                return PartialView("SelfReceipt", returnModel);
            }
            else
            {
                return PartialView("SbiReceipt", returnModel);
            }
        }
        [HttpGet]
        public ActionResult BankCustomer(int BankId)
        {
            Models.ViewModels.BankCustomerModel model = new Models.ViewModels.BankCustomerModel();
            var relList = new[] { new { Name = "Son of", Value = 1 }, new { Name = "Daughter of", Value = 2 }, new { Name = "Wife of", Value = 3 } };
            //model.BankId = BankId;
            model.RelationTypes = relList.Select(x => new SelectListItem
            {
                Value = x.Value.ToString(),
                Text = x.Name
            });
            return PartialView("BankCustomer", model);
        }
        [HttpPost]
        public ActionResult BankCustomer(Models.ViewModels.BankCustomerModel model)
        {
            BL.Interfaces.AppriserInterface bl = new BL.Implementation.AppraiserClass();
            int AppraiserId = LogedUser.AppraiserId.Value;
            string userName = LogedUser.UserName;
            //int BankId = model.BankId;
            //ModelState["ornamentDetails.StoneWeight"].Errors.Clear();
            try
            {
                //if (ModelState.IsValid == false)
                //{
                int customerId = bl.SaveBankCustomerDetails(model, AppraiserId, userName);
                //return RedirectToAction("Estimation", new { customerId = customerId, LoanType = 2 });
                return Json(customerId, JsonRequestBehavior.AllowGet);
                //}
            }
            catch (Exception ex)
            {
                Models.ViewModels.ProcessLoanModel procModel = new Models.ViewModels.ProcessLoanModel();
                procModel.selfCustomer = new Models.ViewModels.SelfCustomerModel();
                procModel.bankCustomer = model;

DigitalAppraiser/Views/Apraiser/CollectLoanDetails.cshtml
@model DigitalAppraiser.Models.DBModels.LoanDetails
@{
    ViewBag.Title = "CollectLoanDetails";
    Layout = "~/Views/Shared/_AppraiserLayout.cshtml";
}
<style>
    .login-form {
        margin-top: 10px;
        box-shadow: 0px 0px 10px 1px grey;
        border-radius: 5px;
        padding-bottom: 20px;
        background: #eee;
    }

    .title {
        background: #007bbf;
        padding: 10px;
        text-align: center;
        color: #fff;
        border-radius: 0px 0px 10px 10px;
    }

    .error {
        color: red;
    }
</style>
<div class="login-form col-md-6 offset-md-3 col-sm-8 offset-sm-2 col-8 offset-2 col-lg-4 offset-lg-4">
    <h1 class="title"> Search Loan ID </h1>
    @using (Html.BeginForm("LoanDetails", "Apraiser", FormMethod.Get, new { id = "formCustomerGetLoan" }))
    {
        <form>
            <div class="form-group form-inline">
                <label class="">Loan ID<span style="color:red">*</span></label>
                @Html.TextBoxFor(x => x.LoanId, new { id = "txtLoanId", @class = "form-control offset-sm-2 offset-md-2 offset-lg-2", autocomplete = "off" })
                @if (ViewBag.LoanNotFound != null)
                {
                    <label class="error">@ViewBag.LoanNotFound</label>
                }
            </div>
            <div class="form-group form-inline">
                <input type="submit" class="btn btn-info offset-4 offset-sm-5 offset-md-5 offset-lg-5" id="btnSubmitLoanId" value="Submit" />
            </div>
        </form>

        @*<div class="col-12 offset-0" style="padding:0px;min-height:200px">
                <div class="h2" style="background-color: #33719b;color: #fff;font-size: 20px;font-weight:bold;">
                    Search Loan ID
                </div>
                <br />
                <div class="row" id="divContainer">

                    <div class="offset-3">
                        <div class="col-9">
                            <div class="col-3">
                                <div class="form-group">
                                    <label class="text-info">Loan ID<span style="color:red">*</span>:</label><br />
                                </div>
                            </div>
                            <div class="col-5">
                                <div class="form-group">
                                    @Html.TextBoxFor(x=>x.LoanId)
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="submit" id="btnSubmitLoanId" value="Submit" class="btn btn-info btn-md col-sm-2 col-sm-offset-5" />
                    <br />
                    <div id="divError" class="alert alert-danger col-4 offset-4" style="display:none;margin-top:1%;">

                    </div>
                </div>

                <div class="row">
                    <div id="divCustomerDetails">

                    </div>
                </div>
            </div>*@
    }
</div>
<script>
    $(document).ready(function () {
        ActiveMenu("liCollectLoan");
    })

                            //GetLoanDetails = function () {
                            //    var isValid = true;
                            //    var errorMsg = "";
                            //    if ($("#txtLoanId").val() == "") {
                            //        isValid = false;
                            //        errorMsg = "Please enter all mandatory fields";
                            //    }
                            //    if (isValid == true) {
                            //        var Url = "/Apraiser/GetLoanDetails";
                            //        $.ajax({
                            //            url: Url,
                            //            type: "GET",
                            //            cache: false,
                            //            data: {
                            //                LoanId: $("#txtLoanId").val()
                            //            },
                            //            success: function (data) {
                            //                debugger;
                            //                if (data == "") {
                            //                    $("#divError").html(data);
                            //                    $("#divError").show();
                            //                } else {
                            //                    $("#divCustomerDetails").html(data);
                            //                    $("#divContainer").hide();
                            //                }
                            //            },
                            //            error: function (error) {

                            //            }
                            //        });
                            //    } else {
                            //        $("#divError").html(errorMsg);
                            //        $("#divError").show();
                            //    }

                            //}
</script>

DigitalAppraiser/Views/Apraiser/PaymentPage.cshtml
@{
    ViewBag.Title = "Payment";
    //Layout = "~/Views/Shared/_AppraiserLayout.cshtml";
}

<h2>Payment</h2>

@Html.Raw(ViewBag.paytm)

DigitalAppraiser/Views/Apraiser/PaytmResponse.cshtml
@{
    ViewBag.Title = "PaytmResponse";
    Layout = "~/Views/Shared/_AppraiserLayout.cshtml";
}

<h2>PaytmResponse</h2>

DigitalAppraiser/Views/Apraiser/SelfCustomer.cshtml
@model DigitalAppraiser.Models.ViewModels.SelfCustomerModel

@using (Html.BeginForm("SelfCustomer", "Apraiser", FormMethod.Post, new { id = "formCustomerSelf" }))
{
    
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 row">
        <div class="col-12 col-sm-12 col-md-6 col-lg-6" style="width:50%;">
            <h3 class="h3 text-center"> Customer Details</h3>
            <div class="form-group form-inline">
                <label class="offset-md-1 offset-lg-1 col-6 col-sm-6 col-md-4 col-lg-4 flexLeft">Date<span style="color:red">*</span></label>
                @Html.TextBoxFor(x => x.selfCustomer.CreatedOn, new { id = "txtCreatedOn", @class = "form-control col-4 col-sm-4 col-md-5 col-lg-5" })
                
                @Html.ValidationMessageFor(x => x.selfCustomer.CreatedOn, "", new { @class = "error offset-6 offset-sm-6 offset-md-6 offset-lg-6" })
            </div>
            <div class="form-group form-inline">
                <label class="offset-md-1 offset-lg-1 col-6 col-sm-6 col-md-4 col-lg-4 flexLeft">Name<span style="color:red">*</span></label>
                @Html.TextBoxFor(x => x.selfCustomer.Name, new { id = "txtName", @class = "form-control col-6 col-sm-6 col-md-6 col-lg-6", autocomplete = "off", @onkeypress = "IsName(event)" })
                @Html.ValidationMessageFor(x => x.selfCustomer.Name, "", new { @class = "error offset-6 offset-sm-6 offset-md-6 offset-lg-6" })
            </div>
            <div class="form-group form-inline">
                <label class="offset-md-1 offset-lg-1 col-6 col-sm-6 col-md-4 col-lg-4 flexLeft">Aadhar</label>
                @Html.TextBoxFor(x => x.selfCustomer.UANNumber, new { id = "txtUANNumber", @class = "form-control col-6 col-sm-6 col-md-6 col-lg-6", @onkeypress = "IsNumeric(event)", @maxlength = "12", autocomplete = "off" })
            </div>
            <div class="form-group form-inline">
                <label class="offset-md-1 offset-lg-1 col-6 col-sm-6 col-md-4 col-lg-4 flexLeft">Mobile Number<span style="color:red">*</span></label>
                @Html.TextBoxFor(x => x.selfCustomer.MobileNumber, new { id = "txtMobileNumber", @class = "form-control col-6 col-sm-6 col-md-6 col-lg-6", @maxlength = "10", @onkeypress = "IsNumeric(event)", autocomplete = "off" })
                @Html.ValidationMessageFor(x => x.selfCustomer.MobileNumber, "", new { @class = "error col-6 offset-6 offset-sm-6 offset-md-6 offset-lg-6" })
            </div>
            <div class="form-group form-inline">
                <label class="offset-md-1 offset-lg-1 col-6 col-sm-6 col-md-4 col-lg-4 flexLeft">Address<span style="color:red">*</span></label>
                @Html.TextAreaFor(x => x.selfCustomer.Address, new { id = "txtAddress", @class = "form-control col-6 col-sm-6 col-md-6 col-lg-6" })
                @Html.ValidationMessageFor(x => x.selfCustomer.Address, "", new { @class = "error offset-6 offset-sm-6 offset-md-6 offset-lg-6" })
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-6 col-lg-6">
            <h3 class="h3 text-center"> Ornament Details</h3>
            <div class="form-group form-inline">
                <label class="col-6 col-sm-6 col-md-4 col-lg-4 flexLeft">Ornament<span style="color:red">*</span></label>
                @Html.TextAreaFor(x => x.ornamentDetails.Ornament, new { id = "txtOrnament", @class = "form-control col-6 col-sm-6 col-md-6 col-lg-6" })
                @Html.ValidationMessageFor(x => x.ornamentDetails.Ornament, "", new { @class = "error offset-6 offset-sm-6 offset-md-4 offset-lg-4" })
            </div>
            <div class="form-group form-inline">
                <label class="col-6 col-sm-6 col-md-4 col-lg-4 flexLeft">Quantity<span style="color:red">*</span></label>
                @Html.DropDownListFor(x => x.ornamentDetails.Quantity, Model.Quantity, "Select", new { id = "ddQuantity", @class = "form-control col-6 col-sm-6 col-md-6 col-lg-6 width100" })
                @Html.ValidationMessageFor(x => x.ornamentDetails.Quantity, "", new { @class = "error offset-6 offset-sm-6 offset-md-4 offset-lg-4" })
            </div>
            <div class="form-group form-inline">
                <label class="col-6 col-sm-6 col-md-4 col-lg-4 flexLeft">Gross weight in grams<span style="color:red">*</span></label>
                @Html.TextBoxFor(x => x.ornamentDetails.GrossWeight, new { Value = "", id = "txtGrossWeight", @class = "form-control col-6 col-sm-6 col-md-6 col-lg-6", @onkeypress = "return IsWeight(event,$(this))", onblur = "CalculateNetWeightAndPrice()", autocomplete = "off" })
                @Html.ValidationMessageFor(x => x.ornamentDetails.GrossWeight, "", new { @class = "error offset-6 offset-sm-6 offset-md-4 offset-lg-4" })
            </div>
            <div class="form-group form-inline">
                <label class="col-6 col-sm-6 col-md-4 col-lg-4 flexLeft">Stone weight in grams</label>
                @Html.TextBoxFor(x => x.ornamentDetails.StoneWeight, new { Value = "", id = "txtStoneWeight", @class = "form-control col-6 col-sm-6 col-md-6 col-lg-6", @onkeypress = "return IsWeight(event,$(this))", onblur = "CalculateNetWeightAndPrice()", autocomplete = "off" })
                @Html.ValidationMessageFor(x => x.ornamentDetails.StoneWeight, "", new { @class = "error offset-6 offset-sm-6 offset-md-4 offset-lg-4" })
            </div>
            <div class="form-group form-inline">
                <label class="col-6 col-sm-6 col-md-4 col-lg-4 flexLeft">Net weight in grams<span style="color:red">*</span></label>
                @Html.TextBoxFor(x => x.ornamentDetails.NetWeight, new { Value = "", id = "txtNetWeight", @class = "form-control col-6 col-sm-6 col-md-6 col-lg-6 disable-color", @readonly = "readonly" })
                @Html.ValidationMessageFor(x => x.ornamentDetails.NetWeight, "", new { @class = "error offset-6 offset-sm-6 offset-md-4 offset-lg-4" })
            </div>
            @*<div class="form-group form-inline">
                <label class="col-6 col-sm-6 col-md-4 col-lg-4 flexLeft">Market Price<span style="color:red">*</span></label>
                @Html.TextBoxFor(x => x.ornamentDetails.MarketPrice, new { id = "txtMarketPrice", @class = "form-control col-6 col-sm-6 col-md-6 col-lg-6" })
                @Html.ValidationMessageFor(x => x.ornamentDetails.MarketPrice, "", new { @class = "error offset-6 offset-sm-6 offset-md-4 offset-lg-4" })
            </div>*@
            
            <div class="form-group offset-6 offset-sm-6 offset-md-4 offset-lg-4 col-6 col-sm-6 col-md-6 col-lg-6">
                <a class="btn btn-danger" href="/Apraiser/ProcessLoan">Cancel</a>&nbsp;&nbsp;
                <input type="submit" class="btn btn-primary float-right" value="Submit" id="btnSubmitSelfForm"/>
            </div>
        </div>
    </div>
}



<script>
    $(document).ready(function () {
        //var TodayRate = $.parseJSON($("#hdnTodayRate").val());
        $("#txtCreatedOn").datepicker({
            dateFormat: "dd-M-yy",
            showOn: "button",
            buttonImage: "/Content/Images/calendar.png",
        }).datepicker("setDate", new Date());
        ActiveMenu("liProcessLoan");
        $("#loader").hide();
        $("#spnCalender").click(function () {
            $("#txtCreatedOn").trigger("click");
        })
    })

    IsNumeric = function (e) {
        if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
            e.preventDefault()
        }
    }
    IsName = function (e) {
        var isValid = false;
        var regex = /^[a-zA-Z\. ]*$/;
        isValid = regex.test(e.key);
        if (isValid == false) {
            e.preventDefault()
            return isValid;
        }
    }
    CalculateNetWeightAndPrice = function () {
        
        //var TodayRate = $.parseJSON($("#hdnTodayRate").val());
        var netWt = 0;
        var marketPrice = 0;
        var grossWt = $("#txtGrossWeight").val() == "" ? 0 : $("#txtGrossWeight").val();
        var stoneWt = $("#txtStoneWeight").val() == "" ? 0 : $("#txtStoneWeight").val();
        //var quality = $("#txtQuality").val() == "" ? 1 : $("#txtQuality").val();
        //if ($("#txtQuality").val() != "") {
            //if (TodayRate.BankId == 1) {
                netWt = (grossWt - stoneWt);// * (quality / 100);

                //marketPrice = netWt * TodayRate.Rate;
            //} else {
            //    var s = (grossWt - stoneWt);// * (quality / 100);
            //    netWt = s + ((s * 8) / 100);
            //   // marketPrice = netWt * TodayRate.Rate;
            //}
            $("#txtNetWeight").val(netWt.toFixed(3));
            //$("#txtMarketPrice").val(marketPrice.toFixed(2));
        //}
    }
    SaveCustomerSelf = function () {
        var isValid = true;
        var errorMsg = "";
        if ($("#txtNameSelf").val() == "") {
            errorMsg = "Please fill all amndatory fields."
            isValid = false;
        }
        //if ($("#txtUANSelf").val() == "") {
        //    errorMsg = "Please fill all amndatory fields."
        //    isValid = false;
        //}
        if ($("#txtMobileSelf").val() == "") {
            errorMsg = "Please fill all amndatory fields."
            isValid = false;
        }
        if ($("#txtAddressSelf").val() == "") {
            errorMsg = "Please fill all amndatory fields."
            isValid = false;
        }

        if (isValid == true) {
            //$("#formCustomerSelf").bind("submit");
            $("#formCustomerSelf").submit(function (e) {
                e.currentTarget.submit();
            });
        } else {
            $("#formCustomerSelf").submit(function (e) {
                e.preventDefault();
            });
            //$("#formCustomerSelf").submit(false);
            $("#divError").html(errorMsg);
            $("#divError").show();
        }
    }
</script>